# Generated by Django 5.2.14 on 2026-06-04 15:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='My Portfolio', max_length=200)),
                ('site_description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('hero_title', models.CharField(default="Hello, I'm", max_length=200)),
                ('hero_name', models.CharField(default='[Your Name]', max_length=100)),
                ('hero_roles', models.JSONField(blank=True, default=list, help_text="List of rotating roles, e.g. ['Developer', 'Researcher']")),
                ('hero_subtitle', models.CharField(default='Building the future, one line of code at a time.', max_length=300)),
                ('meta_keywords', models.TextField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('enable_music', models.BooleanField(default=False)),
                ('music_file', models.FileField(blank=True, null=True, upload_to='music/')),
                ('visitor_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('visited_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('page_views', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['-visited_at'],
            },
        ),
    ]
