# Generated by Django 5.2.14 on 2026-06-07 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_projectimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisitorSession',
        ),
    ]
