# Generated by Django 5.2.14 on 2026-06-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_delete_visitorsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='certificate',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='achievements/'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='achievements/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='blog/'),
        ),
        migrations.AlterField(
            model_name='education',
            name='logo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='education/'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company_logo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='experience/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(max_length=500, upload_to='projects/gallery/'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pdf',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='publications/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='avatar',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='testimonials/'),
        ),
    ]
